### ISSUE TITLE
knight.py problem

### ISSUE THREAD

**Issue by stevencheung03** [mAxYoLo01/Chess#1]
on the line "if tile.postion == self.position:", what is self.postion?

**Comment by mAxYoLo01** [comment]
It checks for each tile in the 8x8 chessboard, and if the current tile is the one where the knight is positioned, then it checks for all the correct moves possible. This code is a year old so I know that there's a lot to improve, but it's cool to see you're interested in it ^^

**Comment by stevencheung03** [comment]
I mean I’m still soo g pre uni computer science, so I’m just trying to understand some advanced code, and hope use some in my code. So what’s the tile.position and self.position? What do they equal as an example?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mAxYoLo01** [comment]
Both positions are tuples of size 2. And they can be between (0, 0) and (7, 7) I believe.

**Comment by stevencheung03** [comment]
Ahh, so it checks of a piece is on that square or tile

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stevencheung03** [comment]
But where are we getting the self.position from? PyCharm is saying it's not fount?

I highly appreciate you helping!!

________________________________
